@startuml
class block.Block {
+ <<Create>> Block(BlockType)
+ <<Create>> Block()
}
abstract class entity.base.Entity {
# String name
# int health
+ <<Create>> Entity()
+ <<Create>> Entity(String)
+ <<Create>> Entity(String,int)
+ String toString()
+ String getName()
+ void setName(String)
+ int getHealth()
+ void setHealth(int)
}
interface entity.base.Attackable {
~ boolean attack(Entity)
}
class scene.Menu {
~ Text title
~ Label label
+ boolean gameStart
+ <<Create>> Menu()
+ void initializeStartText()
}
class entity.derived.BoosterBlock {
+ <<Create>> BoosterBlock()
+ boolean move(int,int)
}
class application.Main {
+ void start(Stage)
+ {static} void main(String[])
}
class application.GameController {
- Player player
- int points
- Timer timeElapsed
- boolean isGameEnd
# int terrainCount
+ <<Create>> GameController()
+ Player getPlayer()
+ void setPlayer(Player)
+ int getPoints()
+ void setPoints(int)
+ void startTimer()
+ boolean isGameEnd()
+ void setGameEnd(boolean)
+ void genLevel(Group)
}
class entity.derived.Coin {
+ void collect()
}
class entity.derived.Player {
- AnimationTimer animationTimer
- double posY
- double posX
- double vx
- double vy
- double ay
- double borderX
- double borderY
- boolean goNextScene
+ <<Create>> Player()
+ <<Create>> Player(String)
+ void initializeMovement()
+ void setAnimationTimer()
+ void returnToBegin()
+ double getBorderX()
+ void setBorderX(double)
+ double getBorderY()
+ double getPosY()
+ void setPosY(double)
+ double getPosX()
+ void setPosX(double)
+ boolean isGoNextScene()
+ void setGoNextScene(boolean)
+ void setBorderY(double)
}
interface entity.base.Movable {
~ boolean move(int,int)
}
interface entity.base.Collectable {
~ void collect()
}
class scene.Terrain {
- int terrainID
+ <<Create>> Terrain(int)
+ void readTerrain()
+ int getTerrainID()
+ void initializeTerrain()
}


javafx.scene.layout.Pane <|-- block.Block
javafx.scene.image.ImageView <|-- entity.base.Entity
javafx.scene.layout.VBox <|-- scene.Menu
entity.base.Movable <|.. entity.derived.BoosterBlock
entity.base.Entity <|-- entity.derived.BoosterBlock
javafx.application.Application <|-- application.Main
entity.base.Collectable <|.. entity.derived.Coin
entity.base.Entity <|-- entity.derived.Coin
entity.base.Entity <|-- entity.derived.Player
javafx.scene.layout.GridPane <|-- scene.Terrain
@enduml